### ISSUE TITLE
Your component is featured on my blog

### ISSUE THREAD

**Issue by binbalenci** [Link2Twenty/l2t-paper-color#9]
Hi Link2Twenty,

How it's going in Conventry? I've never been there, but I have always wanted to travel to UK. Perhaps it will not be that easy anymore after Brexit. 

Nonetheless, I bring good news. Your component, l2t-paper-color, is featured in my latest article on "color picker components". I love how simple and alluring your component is, I think that it can be used in many websites and web apps.

Here's the [link](https://vaadin.com/blog/best-color-picker-component-l2t-paper-color-vs-paper-swatch-picker-vs-color-picker) to the blog. It would be nice to give a shoutout in the comment section so everyone knows who is the mastermind behind the component.

There's a [poll tweet](https://twitter.com/slashpiggie/status/978972661719207936) on "Which component was your favorite?". Additionally, I also shared the blog featuring your component on [LinkedIn](https://www.linkedin.com/feed/update/urn:li:activity:6384739721368604672/) and [Facebook](https://www.facebook.com/photo.php?fbid=1653268244726706&set=a.103959819657564.10074.100001306385787&type=3&theater). That will make sure more people can see how cool your component is 😉

Cheers,
Binh

**Comment by Link2Twenty** [comment]
Thanks for this, I will leave a comment on your blog post 🙂
